Module4 task2
htmlacademy-nodejs/1962321-typoteka-3 pull request #12
Opened 2022-02-25 15:03 UTC by iluha5

2022-02-25 21:09 UTC, Krabaton requested changes

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/categories.e2e.test.js
> +      expect.arrayContaining([`Без рамки`, `Кино`, `Реки`, `Разное`, `Спорт`])
Илья тут дублирование кода идет. Если в mock данных поменять, то тут тоже надо менять. Надо сранивать с mock данными.

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/search.e2e.test.js
> +  test(`Article has correct id`, () => expect(response.body[0].id).toBe(`ddqqMc`));
Опять `ddqqMc` надо вытащить с мок данных

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/articles.e2e.test.js
> +  test(`First article's id equals "oHNLn2"`, () => expect(response.body[0].id).toBe(`oHNLn2`));
Дубль

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/articles.e2e.test.js
> +    .get(`/articles/oHNLn2`)
Вытащить `oHNLn2` из мок данных, и сравнивать тоже с мок данных

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/articles.e2e.test.js
> +  test(`Returns deleted articles`, () => expect(response.body.id).toBe(`oHNLn2`));
Дубль

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/comments.e2e.test.js
> +  test(`The comment with id = ljapTY should be in the response`, () => expect(response.body[0].id).toBe(`ljapTY`));
Дубль

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/comments.e2e.test.js
> +  test(`Should be 2 comments for the article with id = oHNLn2`, () => expect(response.body.length).toBe(2));
Ну почему 2? Ну вытащи массив с мок данных и возьми длину.

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/comments.e2e.test.js
> +  test(`Returns deleted comment`, () => expect(response.body.id).toBe(`ljapTY`));
Дубль

2022-02-25 21:09 UTC, Krabaton commented on src/service/api/comments.e2e.test.js
> +    .expect((res) => expect(res.body.length).toBe(1))
Опять магический 1

2022-02-27 20:15 UTC, iluha5 commented on src/service/api/categories.e2e.test.js
> +      expect.arrayContaining([`Без рамки`, `Кино`, `Реки`, `Разное`, `Спорт`])
Ок, согласен. Все поправлю.

2022-02-28 14:39 UTC, iluha5 commented on src/service/api/categories.e2e.test.js
> +      expect.arrayContaining([`Без рамки`, `Кино`, `Реки`, `Разное`, `Спорт`])
С другой стороны, конкретно в сервисе категорий идет калькуляция общего списка категорий, их из моков можно вытащить только повторяя логику самого сервиса, это не совсем верно (противоречит принципу черного ящика). Предлагаю в этом кейсе все таки захардкодить объект вывода. В остальных кейсах, где идет прямое сравнение с полями моков, вытащу нужные поля из изначального объекта.

2022-02-28 22:03 UTC, merged