Вдохнуть жизнь (module4 task3)
htmlacademy-nodejs/1962321-typoteka-3 pull request #13
Opened 2022-03-02 07:33 UTC by iluha5

2022-03-02 17:57 UTC, Krabaton requested changes

2022-03-02 17:57 UTC, Krabaton commented on src/express/multer.js
> +const upload = multer({storage});
Надо указывать ограничение на загружаемый файл `fileSize`. И добавить проверку на расширение файла `fileFilter`, понятно, что можно обмануть.

2022-03-02 17:57 UTC, Krabaton commented on src/express/multer.js
> +    const uniqueName = nanoid(10);
можно было вместо `nanoid` использовать `RandomUUID` из модуля `crypto`

2022-03-06 11:08 UTC, iluha5 commented on src/express/multer.js
> +const upload = multer({storage});
Ок, сделаю.

2022-03-06 21:10 UTC, iluha5 commented on src/express/multer.js
> +const upload = multer({storage});
Промучался с multer, так и не смог найти способ корректно отловить лимит fileSize. Если лимит срабатывает, могу отловить ошибку только где-то выше роутера, что не подходит. Есть открытое issue - https://github.com/expressjs/multer/issues/602 
Сделал вывод что с лимитами есть проблема, либо я чего-то не знаю. Сильно углубляться не стал здесь.
В итоге сделал обработку этого лимита руками, не в multer.

2022-03-06 21:24 UTC, iluha5 commented on src/express/multer.js
> +    const uniqueName = nanoid(10);
У меня что-то не завелось - `TypeError: crypto.randomUUID is not a function`, хотя деклорации на этот метод находит. Возможно что-то связано с версией ноды. Копать не стал, оставил нано.

2022-03-09 00:12 UTC, merged