module 2 task 2
htmlacademy-nodejs/1962321-typoteka-3 pull request #6
Opened 2022-01-06 16:28 UTC by iluha5

2022-01-06 17:43 UTC, Krabaton requested changes

2022-01-06 17:43 UTC, Krabaton commented on src/helpers/index.js
> +    return fileDate.trim().split(`\n`);
Мало операций. Мы пропускаем пустые строки. Мы пропускаем пустые символы вокруг сообщений. Надо чистить каждую строку и убирать пустые строки.

2022-01-06 17:43 UTC, Krabaton commented on src/helpers/index.js
> +    const titles = await getFileData(path.resolve(MOCK_FILES_NAMES.TITLES));
На самом деле три await это не очень быстро, лучше их всех дождаться Promise.all
```js
const [titles , sentences , categories ] = await Promise.all([
  getFileData(path.resolve(MOCK_FILES_NAMES.TITLES)),
  getFileData(path.resolve(MOCK_FILES_NAMES.SENTENCES)),
  getFileData(path.resolve(MOCK_FILES_NAMES.CATEGORIES))
])
```

2022-01-07 11:44 UTC, iluha5 commented on src/helpers/index.js
> +    return fileDate.trim().split(`\n`);
Добавил проверки.

2022-01-07 11:59 UTC, iluha5 commented on src/helpers/index.js
> +    const titles = await getFileData(path.resolve(MOCK_FILES_NAMES.TITLES));
Поправил также обработку ошибок.

2022-01-09 00:31 UTC, merged