add express with router
htmlacademy-nodejs/1962321-typoteka-3 pull request #8
Opened 2022-01-20 08:46 UTC by iluha5

2022-01-21 02:27 UTC, Krabaton requested changes

2022-01-21 02:27 UTC, Krabaton commented on src/express/routes/main-routes.js
> +mainRouter.get(ROUTES.root, routeController);
Илья пожалуйста убери это и оставь строки. Я хочу читать код и видеть маршрут, а не лазить по файлам в поисках по какому же урлу мы сюда попадаем.

2022-01-21 02:27 UTC, Krabaton commented on src/literals/routes.js
> +module.exports = ROUTES;
Этот убрать совсем, но если экспортируешь константу то `module.exports = {ROUTES}`

2022-01-21 02:27 UTC, Krabaton commented on src/express/routes/articles-routes.js
> +const routeController = (req, res) => res.send(req.originalUrl);
Насколько я помню правильный путь всегда дает `req.path` именно с params

2022-01-21 02:27 UTC, Krabaton commented on src/express/express.js
> +app.use(routes.root, mainRouter);
Строки, а не переменную, не надо прятать маршруты

2022-01-23 10:11 UTC, iluha5 commented on src/express/routes/main-routes.js
> +mainRouter.get(ROUTES.root, routeController);
Парирую, эти литералы в будущем наверняка будут использовать еще где-то, имеет смысл их вынести в константы, чтобы управлять в одном месте. В рамках курса, вынесу.

2022-01-23 10:15 UTC, iluha5 commented on src/literals/routes.js
> +module.exports = ROUTES;
Есть причина зачем так делать? Просто удобнее и локаничнее импортировать без лишнего ключа. Либо могу избавится от избыточной переменной `ROUTES` и положить все сразу в `module.exports = { ... }`?

2022-01-23 10:20 UTC, iluha5 commented on src/express/routes/main-routes.js
> +mainRouter.get(ROUTES.root, routeController);
Можем договориться, что я буду по минимуму выносить литералы и оставлять их захардкожеными, если так удобнее и быстрее читать. Но только в рамках курса, на будущее вижу правильным выносить роуты.

2022-01-23 10:26 UTC, iluha5 commented on src/express/routes/articles-routes.js
> +const routeController = (req, res) => res.send(req.originalUrl);
`req.path` отдаст только часть uri, в данном случае только `/:id`, вместо `/articles/:id`, по этому взял `path.originalUrl`.

2022-01-23 10:26 UTC, iluha5 commented on src/express/express.js
> +app.use(routes.root, mainRouter);
Ок, поправлю.

2022-01-23 10:34 UTC, iluha5 commented on src/literals/routes.js
> +module.exports = ROUTES;
Убрал этот файл в итоге.

2022-01-24 17:29 UTC, Krabaton commented on src/literals/routes.js
> +module.exports = ROUTES;
Чтобы экспортировать именно `ROUTES `

2022-01-24 17:45 UTC, Krabaton commented on src/express/routes/main-routes.js
> +mainRouter.get(ROUTES.root, routeController);
Нет. Маршруты по REST будут одноразовыми для обработчика и их не надо прятать. Это не правильно и дальнейшем принесет только неудобства в плане чтения кода.  Скажем так - это не тот случай, когда значения надо прятать в перменные и есть плохая практика.

2022-01-24 17:47 UTC, merged

2022-01-26 18:30 UTC, iluha5 commented on src/literals/routes.js
> +module.exports = ROUTES;
Согласен.

2022-01-26 18:30 UTC, iluha5 commented on src/express/routes/main-routes.js
> +mainRouter.get(ROUTES.root, routeController);
Ок