Module3 task2
htmlacademy-nodejs/1962321-typoteka-3 pull request #9
Opened 2022-01-26 18:26 UTC by iluha5

2022-01-28 01:25 UTC, Krabaton requested changes

2022-01-28 01:25 UTC, Krabaton commented on src/express/express.js
> +app.get(`*`, (req, res) => {
Немного странно выглядит. Первое надо использовать `app.use` так как глагол HTTP метода может быть разным, а не только `get`.  `app.get('*' ...` в основном используется типа проверка cookie или еще, чего-то. Потом второе - нет обработки ошибки 500 и что сервер должен делать в случае падения.

Более оправданым будет, что-то типа такого:

```js
// 404 которая для express по сути не ошибка
app.use((_req, res) => {
  return res.status(HttpCode.NOT_FOUND).render(`errors/404`, {
    errorCode: HttpCode.NOT_FOUND,
  });
});

// обработка ошибки, express поймет если мы ему передадим 4 параметра, для него это тогда обработчик ошибок

app.use((err, _req, res, next) => {
  // логируем err
  return res.status(HttpCode.INTERNAL_SERVER_ERROR).render(`errors/500`, {
    errorCode: HttpCode.INTERNAL_SERVER_ERROR,
  });
});
```

2022-01-28 01:25 UTC, Krabaton commented on src/express/templates/all-categories.pug
> +        li.category__list-item
Когда начнем работать с БД это надо будет выводить в циклах.

2022-01-28 01:25 UTC, Krabaton commented on src/express/express.js
> +app.get(`*`, (req, res) => {
[Error Handling](https://expressjs.com/en/guide/error-handling.html)

2022-01-29 08:12 UTC, iluha5 commented on src/express/express.js
> +app.get(`*`, (req, res) => {
Хорошо, спасибо.

2022-01-29 08:12 UTC, iluha5 commented on src/express/templates/all-categories.pug
> +        li.category__list-item
Да, понимаю. В рамках задачи предложено оставить хардоком.

2022-02-01 00:51 UTC, merged